<div style="flex: 1 1 150px;">
    <table>
        <tr>
            <th>Name</th>
            <td><?=$unit->name?></td>
            <td></td>
        </tr>
        <tr>
            <th>Job</th>
            <td><?=$jobs[$unit->job_id]->name?></td>
            <td></td>
        </tr>
        <tr>
            <th>HP</th>
            <td><?=$unit->hp?>/100</td>
            <td></td>
        </tr>
        <tr>
            <th>MP</th>
            <td><?=$unit->mp?>/100</td>
            <td></td>
        </tr>
        <tr>
            <th>STR</th>
            <td><?=$unit->str?></td>
            <td><?=format_gain(@$u["gains"]["str"])?></td>
        </tr>
        <tr>
            <th>AGL</th>
            <td><?=$unit->agl?></td>
            <td><?=format_gain(@$u["gains"]["agl"])?></td>
        </tr>
        <tr>
            <th>MAG</th>
            <td><?=$unit->mag?></td>
            <td><?=format_gain(@$u["gains"]["mag"])?></td>
        </tr>
        <tr>
            <th>STA</th>
            <td><?=$unit->sta?>/100</td>
        </tr>
    </table>
</div>